- wine-staging-esync-pba/PKGBUILD
Doesn't work properly if there are more than one user patches. Also, optionally add d3d9 gallium nine patches.
> wine-esync-staging-pba: fix user patches detection

- wine-tkg-git/PKGBUILD
- wine-tkg-git/customization.cfg
- wine-tkg-git/launch-with-dedicated-gpu-desktop-entry.patch
Hello,
would you consider adding this small patch? Does a favor for users that have laptop with switchable graphics and mesa drivers, will make an additional desktop entry which runs wine with DRI_PRIME set to 1 so it is not necessary to always set this variable via e.g. command line to make it run on dedicated gpu.
Thank you.
> launch with dedicated gpu desktop entry patch

- wine-tkg-git/PKGBUILD
- wine-tkg-git/customization.cfg
This PR proposes the following changes to the `wine-tkg-git` PKGBUILD:
1. Move the patch choices from `pkgver` to `pkgname`. This makes it significantly easier to handle multiple different builds e.g. in a single local repository. This generates package names like `wine-tkg-staging-esync-pba-git`.
2. Also show the low latency patch in `pkgname` (as `-osu`), because the customization.cfg itself states "Using this patch for something else than Osu! isn't recommended".
3. Same for `$_OPTIMIZED`, because it may be relevant if handling multiple versions across different machines.
4. Allow to install into a subdirectory of `/opt`, instead of the default `/usr`. This allows to have multiple different versions installed at the same time.
If this option is enabled, the conf file in binfmt.d will …
> Improvements to wine-tkg-git

- wine-tkg-git/PKGBUILD
- wine-tkg-git/customization.cfg
Adding gcc7 for _COMPILEWITH option.
https://bugs.winehq.org/show_bug.cgi?id=45199
> Add building with gcc7 (for bypass bug 45199)

- wine-tkg-git/PKGBUILD
- wine-tkg-git/customization.cfg
- wine-tkg-git/wine-tkg-patches/valve_proton_fullscreen_hack-staging.patch
#44 The PR adds the patches used by Valve's Proton WINE fork in order to prevent games from changing the desktop resolution of the system when adjusting in-game resolution
The patch only applies to wine-staging and not base-wine.
Also it does not work in combination with Gallium Nine or any game with a native Vulkan renderer.
The patch has been tested with Shadow Warrior 2 and Overwatch using DXVK
> Add fullscreen hack from Valve's Proton WINE fork

- wine-tkg-git/customization.cfg
Orginally about IMAGE_FILE_LARGE_ADDRESS_AWARE failing if WINE is not >=3.19
**3.17:**
```  -I../../../../wine-git/dlls/nvapi/tests -I../../../include -I../../../..
git/include \
-D__WINESRC__ -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdecl
n-after-statement \
-Wempty-body -Wignored-qualifiers -Wno-packed-not-aligned -Wshift-overfl
Wstrict-prototypes \
-Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer
-Wlogical-op \
-D_FORTIFY_SOURCE=2 -march=native -pipe -Os -U_FORTIFY_SOURCE -D_FORTIFY
E=0
gcc -m64 -c -o testlist.o testlist.c -I. -I../../../../wine-git/dlls/nvapi
-I../../../include \
-I../../../../wine-git/include -D__WINESRC__ -D_REENTRANT -fPIC -Wall -p
no-strict-aliasing \
-Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Wno-pac …
```
> Customization improvements

- wine-tkg-git/wine-tkg-patches/mtga.patch
To overwrite target files in all circumstances during msi reinstallation.
The detailed explanation could be found here: https://forums.mtgarena.com/forums/threads/52935/comments/292704
and https://forums.mtgarena.com/forums/threads/53435
In a nutshell: MTGA failed to update one of critical files bcs its version and filesize doesn't change (while content changes). This deadlocks player after update, left him with outdated client version and forces user to completely recreate prefix.
As lutris installs dotnet etc. at runtime this might affect installation performance. Ideally, patched msi.dll/msi.dll.so should be copied at the end of prefix setup.
Anyway, let's discuss.
> Patch msi.dll for mtga

- wine-tkg-git/README.md
Without rephrasing anything (yet!), just utilized GitHub's markdown link to point directly to appropriate README.md and removed a double space while at it.
> Added link to readme and removed double space

- wine-tkg-git/customization.cfg
As `#tag=` is basically a glorified alias for `#commit=`, this is much easier than manually finding out the specific release commit beforehand.
(makepkg checks whether a tag is actually a valid tag if you use `#tag=`, which obviously won't happen here. Checkout will simply fail.)
> Mention using version tags where it's possible

- wine-tkg-git/wine-tkg-profiles/wine-tkg-lutris-oldnvidia-sims3.cfg
Because all other files don't have it already
> Removed " ###" from USER PATCHES section

- linux50-tkg/PKGBUILD
- linux50-tkg/customization.cfg
Useful in case you need a specific module that is not in modprobed db.
> linux50-tkg: Ask for menuconfig before building the kernel

- mingw/mingw-on-arch-automator.sh
I use .pkg.xz on my system and that doesn't work the the loop by default.  Changing it to *.pkg.* should catch other archive formats in use.
> mingw: mingwloop should catch all pkg formats

- faudio-git/PKGBUILD
The license was changed on the Feb 20, 2018 to Zlib - https://github.com/FNA-XNA/FAudio/commit/6c679d121fd421a22ae87315ae5753bdb18db975
> Correct license

- proton-tkg/proton_template/conf/proton
When checking if multiple strings were in config_opts
the checked strings were chained together with 'or'. This construct,
when evaluated, always returned the first string which was then checked
whether it is in the list or not.
This caused the other arguments to be ignored.
Fixes #216
> Fix errors when checking if multiple strings are in config_opts

- proton-tkg/proton_template/conf/user_settings.py
* Removed mention about renaming – compared to regular proton, proton-tkg already ships the file renamed and enabled by default.
* Made `WINE_MONO_TRACE` commented out by default like the others.
* Moved default `WINEDEBUG` options to variable like the others (it's commented by default anyway).
* Renamed gl-based -> OpenGL-based like the others.
Side effect is making the comments a bit more up to date with the Valve's `user_settings.sample.py`. :)
> Minor default `user_settings.py` improvements

- wine-tkg-git/PKGBUILD
- wine-tkg-git/customization.cfg
- wine-tkg-git/wine-tkg-profiles/wine-tkg-mainline.cfg
- wine-tkg-git/wine-tkg-profiles/wine-tkg-staging.cfg
- wine-tkg-git/wine-tkg-profiles/wine-tkg.cfg
I don't think C++ or Objective-C are used anywhere, but it can't hurt to have the options right?
> Add compiler flag options for cross-compilation

- dxvk-tools/updxvk
You need to set `_use_dxvk="prebuilt"` now instead of `_use_dxvk_winelib="false"` same as for d9vk, but since it's not mentioned in [upd9vk](upd9vk) either, let's just drop this note.
> Removed redundant note

- mingw/mingw-on-arch-automator.sh
Mentioned it on Discord yesterday; it seems mingw-w64-cmake is needed for mingw-w64-sdl2. Adding that to my local script made mingw-w64-sdl2 build successfully for me.
> mingw-w64-cmake is needed to build mingw-w64-sdl2

- wine-tkg-git/customization.cfg
Fixing comment added in eb3cd9ea2c6a533e7a15ffa5fe752754c21a2d7c, blame my OCD :frog:
> typo: merge -> merged

- wine-tkg-git/wine-tkg-patches/misc/proton_FS_hack_refreshrate.patch
Currently the fake refresh rate option causes this error to be spammed whenever you run wine:
`0043:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (88) exceeded`
The extra modes still seem to appear in game though. The fix is to copy the realmodes patch and double the maximum modes available.
> wine-tkg-git: Fix 'Maximum modes exceeded' errors caused by refresh rate patch

- wine-tkg-git/customization.cfg
- wine-tkg-git/wine-tkg-scripts/prepare.sh
I think I've done this right?
https://github.com/wine-mirror/wine/commit/cb703739e5c138e3beffab321b84edb129156000
https://github.com/wine-staging/wine-staging/commit/6bee4b6e761613015feba1feaa8d20a569b72a4a
Changed default to false
Otherwise:
```
-> Applying revert-c6b6935.patch
patching file dlls/winex11.drv/window.c
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file dlls/winex11.drv/window.c.rej
==> ERROR: A failure occurred in prepare().
```
> wine-tkg-git: disable revert-c6b6935.patch above wine cb70373

- linux419-tkg/PKGBUILD
- linux419-tkg/customization.cfg
- linux419-tkg/linux419-tkg-patches/0011-umip-instruction-emulation.patch
- linux51-tkg/PKGBUILD
- linux51-tkg/customization.cfg
- linux51-tkg/linux51-tkg-patches/0013-umip-instruction-emulation.patch
- linux52-tkg/PKGBUILD
- linux52-tkg/customization.cfg
- linux52-tkg/linux52-tkg-patches/0015-umip-instruction-emulation.patch
- linux53-tkg/PKGBUILD
- linux53-tkg/customization.cfg
- linux53-tkg/linux53-tkg-patches/0010-umip-instruction-emulation.patch
Could be useful for newer processors. I think I've done all I need to do modifying the PKGBUILD's and whatnot. Builds fine for all kernels.
Only useful until [wine is patched](https://bugs.winehq.org/show_bug.cgi?id=47571#c9) to fix this I guess
https://bugs.winehq.org/show_bug.cgi?id=47571
https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86-asm-for-linus&id=e86c2c8b9380440bbe761b8e2f63ab6b04a45ac2
https://github.com/torvalds/linux/commit/df4c0b18f2a2798f1e3ae9dcf58c024bb33e4202#diff-62728468f7c3625a13900e520e029911
> linux-tkg:  add patch for umip instruction emulation

- mesa-git/PKGBUILD
- mesa-git/README.md
- mesa-git/customization.cfg
- mesa-git/mesa-userpatches/radv_lower_sub.mymesapatch
- mesa-git/mesa-userpatches/re-add_incorrect_pkg-config_files_with_GLVND_for_backward_compatibility.mymesarevert
The main bulk of ACO has been merged into mesa/mesa [bar a few commits](https://gitlab.freedesktop.org/daniel-schuermann/mesa/-/branches/active). As for daniel-schuermann/mesa master, that is only 2 commits ahead of mesa/mesa master, so I've added a patch which includes those two commits. 
Closes https://github.com/Tk-Glitch/PKGBUILDS/issues/312
> mesa-git: remove 'aco' option, add patch with difference

- community-patches/dxvk/nativeopt-when-using-dxvk-win32-thread-model-support.dxvkpatch
When using the "dxvk-win32-thread-model-support" community patch the native opt
patch fails.  This patch expects '_nativeopt="false"' in "updxvk.cfg" because
the standard native opt patch works just fine when win32-thread isn't in use.
[Ticket: None]
> community/dxvk-tools: win32-nativeopt patch

- spirv-tools-git/PKGBUILD
generates :
```
usr/lib/libSPIRV-Tools-link.so
usr/lib/libSPIRV-Tools-opt.so
usr/lib/libSPIRV-Tools-reduce.so
usr/lib/libSPIRV-Tools.so
```
required for programs such as mpv
`mpv: error while loading shared libraries: libSPIRV-Tools.so: cannot open shared object file: No such file or directory`
> spirv-tools-git: produce shared libs

- nvidia-all/PKGBUILD
- The allocator library doesn't get installed because Bash's double bracket doesn't expand globs. And there's no need to use a wildcard here anyways.
- Added lib32 version of the library
> nvidia-all: Fix allocator library

- community-patches/linux419-tkg/README.md
- community-patches/linux419-tkg/amd-mckl-switching.mypatch
- community-patches/linux52-tkg/README.md
- community-patches/linux52-tkg/amd-mckl-switching.mypatch
- community-patches/linux53-tkg/README.md
- community-patches/linux53-tkg/amd-mckl-switching.mypatch
```
This patch set enables mclk switching with multiple monitors when all
monitors are sync.  Normally mclk switching is not available with
multiple monitors because the vblank timing does not line up.  However,
if the timing is identical, the display driver can sync up the displays
in some cases.  Check for these cases and allow mclk switch when
possible.
```
https://lists.freedesktop.org/archives/amd-gfx/2019-August/039006.html
Closes #319
> community-patches: linux419/52/53: amd mclk switching patch

- vulkan-headers-git/PKGBUILD
using yay with `vulkan-headers-git` uses [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vulkan-headers-git) if new commit is detected. As it says in the readme, that package is incomplete, so it's better to not have an aur helper think they're the same
> vulkan-headers-git: differentiate from aur package

- mingw/mingw-on-arch-automator.sh
To allow rebuilding all packages instead of reusing existing packages from the
previous builds to help prevent possible compiler issues whenever the script is
ran.
[Ticket: none]
> mingw:  add --force to makepkg

- mingw/mingw-on-arch-automator.sh
better way of doing #355, in my opinion
haven't testing building but should work
well, it's not exactly passing the argument to makepkg but close enough
> mingw: pass '-f / --force' argument to makepkg

- vkd3d-git/PKGBUILD
- vkd3d-git/customization.cfg
The ['staging' repo](https://github.com/HansKristian-Work/vkd3d) is rarely updated, and not exactly staging in the same sense that wine-staging is. 
Removed this in favour of setting a custom repo, no functional change if you just put in `_vkd3d_source="https://github.com/HansKristian-Work/vkd3d"`
> vkd3d: remove staging, add custom repo option

- mingw/mingw-on-arch-automator.sh
The 7.0.0 sources contain a folder named 6.0.0 so this adds a patch to work
around that issue until either mingw fixes this issue on their end or the AUR
PKGBUILD adopts this or another workaround like renaming the folder.
mingw: mingw-w64-crt 6.0.0 folder in 7.0.0 sources
The 7.0.0 sources contain a folder named 6.0.0 so this adds a patch to work
around that issue until either mingw fixes this issue on their end or the AUR
PKGBUILD adopts this or another workaround like renaming the folder.
What's the enter key for again?
mingw: mingw-w64-crt patch sha256sum
Patch the checksum to the correct one
mingw: more 7.0.0 workarounds
> mingw: mingw-w64-headers 6.0.0 folder in 7.0.0 sources

- mingw/mingw-on-arch-automator.sh
#357 never actually worked since a function has it's own arguments, we need to pass through the script's.
> mingw: fix passing through of force argument

- wine-tkg-git/PKGBUILD
Currently if you use the hidden option `_staging_upstreamignore` you're forced to use wine master since `_use_staging` would be true in such a case and thus `_plain_commit`  wouldn't be set.
> wine-tkg-git: Add another use case for _plain_version

- mesa-git/PKGBUILD
xorgproto was refactored, all legacy headers were cleaned up. 
The xorgproto package no longer provides glproto, dri2proto, dri3proto and presentproto.
> Replace *proto with xorgproto

- linux55-rc-tkg/PKGBUILD
Fixed compilation with diffconfig/nconfig being enabled for RC kernel
> linux55-rc-tkg: Fixed compilation with *config

- mesa-git/PKGBUILD
- mesa-git/customization.cfg
MangoHud is now standalone, so the mesa repo is not going to be updated anymore and is pretty far out of date already
> mesa-git: remove mangohud option

- linux55-tkg/linux55-tkg-patches/0005-glitched-pds.patch
Make sure you cannot select UCLAMP_TASK when using PDS scheduler. This is done with BMQ for kernel > 5.3, but since PDS is no longer actively developed this has not been added.
> Update Kconfig for PDS

- linux56-rc-tkg/PKGBUILD
I think it happened for 55-rc as well?
> linux56-rc-tkg: Fix for diffconfig not applying

- nvidia-all/PKGBUILD
Without this gnome and other DEs can be unusable
> nvidia-all: Fixes completely broken application profiles

- proton-tkg/README.md
I find the README a bit confusing and also incorrect, so I changed it a bit.
> proton-tkg: Fix README default option values and make it more clear
