Tk-Glitch/PKGBUILDS

wine-tkg-git/PKGBUILD
Just a small mistake made it not working.
=> wine-tkg-git: fix user revert patches applying

wine-tkg-git/PKGBUILD, wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-patches/mtga-staging.patch, wine-tkg-git/wine-tkg-patches/mtga.patch
Fixes https://bugs.winehq.org/show_bug.cgi?id=45546
=> Added fix for Magic The Gathering: Arena

wine-tkg-git/PKGBUILD, wine-tkg-git/wine-tkg-patches/valve_proton_fullscreen_hack-staging.patch
Tested for several hours using DOOM 2016 with both Vulkan and OpenGL renderer
=> Update fullscreen hack with Vulkan support

wine-tkg-git/PKGBUILD
No need to make this more complicated than it has to be.
=> wine-tkg-git: simplify git-log queries

wine-tkg-git/PKGBUILD, wine-tkg-git/README.md, wine-tkg-git/customization.cfg
Solves https://github.com/Tk-Glitch/PKGBUILDS/issues/73
=> Fix Gallium Nine not patching

wine-tkg-git/PKGBUILD
Follow-up to #56. No idea why I never actually committed it.
=> wine-tkg-git: Improve preparation speed

linux419-tkg/README.md
Made my repo nice and added support for LTS.
=> Add Gentoo notice to linux419-tkg.

wine-tkg-git/PKGBUILD
This is probably bugging me more than it should.
=> wine-tkg-git: Use arrays instead of many variables

dxvk-tools/README.md
Added a note about mingw being needed to compile, took me a while to figure so could be useful.
=> Rough note about mingw being needed

linux420-tkg/customization.cfg
Added missing quotation mark to "true", just like in the comments below
=> Missing quotation mark in comments

wine-tkg-git/PKGBUILD, wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-patches/dxvk-async.patch
incase anyone doesn't like stuttering in OW/PoE
=> Add DXVK Async patches

proton-tkg/proton-tkg.sh
I haven't tried your script yet but manually building 32-bit lsteamclient.dll.so this way worked.
=> Fix 32-bit build of lsteamclient.dll.so

wine-tkg-git/PKGBUILD
"Let me just quickly rebuild wine to test this out"
(one eternity later)
Alright it works now
=> wine-tkg-git: Redetermine _realwineversion during package() if necessary

proton-tkg/userpatches/amd-ags.mypatch
Change malformed UTF-8 strings of "Józef Kucia" to actual strings. Hopefully found them all and the script still works (it should).
=> Can't into UTF-8?

wine-tkg-git/PKGBUILD
Your indentation is giving my vim a headache. :(
=> wine-tkg-git: List found userpatches when asking

dxvk-tools/upd9vk, dxvk-tools/updxvk
Adds symlinks in output dir which point to the latest build to use in scripts instead of fiddling with the last-head text file
=> add symlinks to latest builds

linux51-tkg/PKGBUILD
=> Fix BMQ patching

README.md
**A comprehensive script allowing for interaction with multiple distros at once, being used in unison or isolated if the need arises, in a mostly "just works" state.**
Here's some of what I installed using an Arch 'strat':
Running a UE4 game, it's what I had on my _(NTFS)_ drive that utilizes DXVK, and doesn't crash from Steam not being installed:
I used the non-DKMS version of nvidia-all for GPU acceleration, it has to be the same version for all stratas (distros), see: https://bedrocklinux.org/0.7/compatibility-and-workarounds.html
I'd say it works very well for the week I've been using it, it's a very real project and reading through the site will tell you such with clarity.
=> Mention Bedrock Linux

wine-tkg-git/wine-tkg-profiles/wine-tkg-lutris.changelog
=> Fixed typo

linux51-tkg/customization.cfg
…and missing spaces. Effectively reverts 5d71585 :frog:
=> Welcome back MuQSS

linux419-tkg/PKGBUILD, linux50-tkg/PKGBUILD, linux51-tkg/PKGBUILD, linux52-rc-tkg/PKGBUILD
Fixes not being able to build again after sending interrupt during menuconfig for me. Also removed -r for file checks and added 5.2 of frog.
=> linux-TkG: add customization.cfg to NUKR & misc options

dxvk-tools/updxvk
Winelib support was removed some time ago
=> Remove mention of winelib

dxvk-tools/upd9vk
=> dxvk-tools: Fix ./upd9vk lutris-dxvk

proton-tkg/proton_template/conf/user_settings.py
winelib dxvk/d9vk are no longer with us 🕯️
=> proton-tkg: removed winelib mentions

dxvk-tools/DXVKBUILD/patches/dxvk_mango.dxvkpatchb
https://github.com/flightlessmango/dxvk/commits/mangohud
excludes readme change
=> dxvk-tools: update mangohud to dd5692d

dxvk-tools/updxvk
=> dxvk-tools: fix mangohud fallback patch (whoops)

wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-scripts/prepare.sh
Nothing to patch on non-staging
Fixes https://github.com/Tk-Glitch/PKGBUILDS/issues/323
=> wine-tkg-git: disable nvidia-hate.patch on non staging

dxvk-tools/DXVKBUILD/patches/dxvk_mangohud.dxvkpatchb, dxvk-tools/updxvk
switching to diff squashes all commits, was failing to build otherwise
=> dxvk-tools: fix mangohud patch

.gitignore
=> .gitignore: match vulkan-headers-git changes

community-patches/vkd3d-git/wow-flicker-fix.myvkd3dpatch
https://bugs.winehq.org/show_bug.cgi?id=46410#c21
=> vkd3d: update wow-flicker-fix patch 

mingw/mingw-on-arch-automator.sh
It seems that the folder names are now correct (v7.0.0)
=> mingw: remove folder name changes, fixes build & fixes #386

community-patches/wine-tkg-git/README.md
=> wine-tkg-git Fixed typo in readme

faudio-git/PKGBUILD
```
Package (2)           Old Version      New Version           Net Change
faudio-tkg-git        r1259.df1349b-1  20.01.r15.gdf1349b-1    0.00 MiB
lib32-faudio-tkg-git  r1259.df1349b-1  20.01.r15.gdf1349b-1    0.00 MiB
```
=> faudio-git: change package version naming

community-patches/linux55-tkg/README.md, community-patches/linux55-tkg/wireguard.mypatch
=> community-patches: linux55: add wireguard patch

community-patches/wine-tkg-git/README.md, community-patches/wine-tkg-git/blackops2_unhandled_exception_fix.mypatch
https://bugs.winehq.org/show_bug.cgi?id=46472
=> community-patches: wine-tkg: Add blackops2_unhandled_exception_fix - 

linux55-tkg/PKGBUILD
=> Fix sed-expression missing the closing delimiter

linux54-tkg/PKGBUILD, linux55-tkg/PKGBUILD, linux56-rc-tkg/PKGBUILD
Should fix https://github.com/Tk-Glitch/PKGBUILDS/pull/493#issuecomment-586742945
=> Diffconfig changes

wine-tkg-git/README.md
Firerat switched to gitlab, and deleted his previous account here on GitHub, Hi Etienne, it would be good for you to take a look at this repository it seems that Firerat worked a little more here. Have a nice day :relaxed:.
=> Link broken by a Functional:

community-patches/wine-tkg-git/NFSWLauncherfix.mypatch, community-patches/wine-tkg-git/README.md
from https://github.com/SoapboxRaceWorld/wine
=> community-patches: wine-tkg-git: add NFSW Launcher fix
